/** PRODUCTOS */
export const OBTENER_PRODUCTOS ='OBTENER_PRODUCTOS';
export const AGREGAR_PRODUCTOS ='AGREGAR_PRODUCTOS';
export const MODIFICAR_PRODUCTOS ='MODIFICAR_PRODUCTOS';
export const ELIMINAR_PRODUCTOS ='ELIMINAR_PRODUCTOS';
export const PRODUCTO_ACTUAL = 'PRODUCTO_ACTUAL';

/** CARRITO */
export const OBTENER_CARRITO = 'OBTENER_CARRITO';
export const AGREGAR_CARRITO = 'AGREGAR_CARRITO';
export const ELIMINAR_CARRITO = 'ELIMINAR_CARRITO';
export const EDITAR_CARRITO = 'EDITAR_CARRITO';
export const VACIAR_CARRITO = 'VACIAR_CARRITO';
export const MOSTRAR_CARRITO = 'MOSTRAT_CARRITO';


/** CALCULO DE TOTAL */
export const OBTENER_TOTAL = 'OBTENER_TOTAL';

/** ALERTA */
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';



/** AUTENTICACION */
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const UPDATE_EXITOSO = 'UPDATE_EXITOSO';


/* USUARIOS */
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const ASIGNAR_ROL = 'ASIGNAR_ROL';


/* ORDENES */
export const OBTENER_PEDIDOS = 'OBTENER_PEDIDOS';
export const OBTENER_PEDIDOS_USUARIO = 'OBTENER_PEDIDOS_USUARIO';
export const GENERAR_PEDIDOS = 'GENERAR_PEDIDOS';
export const ELIMINAR_PEDIDOS = 'ELIMINAR_PEDIDOS';
export const MODIFICAR_PEDIDOS = 'MODIFICAR_PEDIDOS';
export const MEJORES_CLIENTES = 'MEJORES_CLIENTES';
export const PRODUCTOS_MAS_VENDIDO = 'PRODUCTOS_MAS_VENDIDO';
export const PEDIDOS_RECIENTES = 'PEDIDOS_RECIENTES';
export const PEDIDOS_PENDIENTES = 'PEDIDOS_PENDIENTES';

